#!/bin/sh
#
# Copyright (c) 2001-2014. NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# See file LICENSE for terms.
#

#
# UCX build for maximal performance while maintaining portability.
# No extra debugging or profiling code.
#

basedir=$(cd $(dirname $0) && pwd)
$basedir/../configure \
	--disable-logging \
	--disable-debug \
	--disable-assertions \
	--disable-params-check \
	"$@"
