#!/bin/sh
#
# Copyright (c) 2001-2019. NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# See file LICENSE for terms.
#

#
# UCX build for maximal performance, use non-portable CPU optimizations.
# No extra debugging or profiling code.
#

basedir=$(cd $(dirname $0) && pwd)
$basedir/configure-release \
	--enable-optimizations \
	"$@"
