#!/bin/sh
#
# Copyright (c) 2001-2014. NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# See file LICENSE for terms.
#

#
# UCX build for profiling purposes.
# Some extra code to ease performance debugging.
#

basedir=$(cd $(dirname $0) && pwd)
$basedir/../configure \
	--disable-logging \
	--disable-debug \
	--disable-assertions \
	--disable-params-check \
	--enable-backtrace-detail \
	--enable-profiling \
	--enable-frame-pointer \
	--enable-stats \
	"$@"
