# See https://aka.ms/yaml

trigger: none

resources:
  pipelines:
  - pipeline: myTest
    source: 'UCX snapshot'
    trigger: true

stages:
  - stage: Rebase
    jobs:
      - job: rebase
        displayName: rebase from openucx/ucx@master
        steps:
          - bash: |
              set -x
              git checkout avildema-patch-1
              git remote add upstream git@github.com:openucx/ucx.git
              git fetch upstream
              git rebase upstream/master
              git push origin HEAD --force

