#
# Copyright (c) 2020. NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# See file LICENSE for terms.
#

noinst_LTLIBRARIES          = libucs_vfs_sock.la
libucs_vfs_sock_la_SOURCES  = vfs_sock.c
noinst_HEADERS              = vfs_sock.h
libucs_vfs_sock_la_CPPFLAGS = $(BASE_CPPFLAGS)
libucs_vfs_sock_la_LDFLAGS  = $(BASE_LDFLAGS)
